import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"; // Importieren Sie die neue Datei

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SEO Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={inter.className}>
        {/* Wickeln Sie die "children" in den Provider ein */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
